// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { HealthApiHealthGetData, HealthApiHealthGetResponses, LiveApiLiveGetData, LiveApiLiveGetResponses, ReadyApiReadyGetData, ReadyApiReadyGetErrors, ReadyApiReadyGetResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Live
 */
export const liveApiLiveGet = <ThrowOnError extends boolean = false>(options?: Options<LiveApiLiveGetData, ThrowOnError>) => (options?.client ?? client).get<LiveApiLiveGetResponses, unknown, ThrowOnError>({ url: '/api/live', ...options });

/**
 * Ready
 */
export const readyApiReadyGet = <ThrowOnError extends boolean = false>(options?: Options<ReadyApiReadyGetData, ThrowOnError>) => (options?.client ?? client).get<ReadyApiReadyGetResponses, ReadyApiReadyGetErrors, ThrowOnError>({ url: '/api/ready', ...options });

/**
 * Health
 */
export const healthApiHealthGet = <ThrowOnError extends boolean = false>(options?: Options<HealthApiHealthGetData, ThrowOnError>) => (options?.client ?? client).get<HealthApiHealthGetResponses, unknown, ThrowOnError>({ url: '/api/health', ...options });
